# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/107wB1aK0RQi3gCb6fjv5JwHz8JPJeVd2
"""

import pandas as pd 
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

from sklearn import metrics
from sklearn.model_selection import train_test_split
df = pd.read_csv("/content/LR.csv")
print(df)
X = df[['Weight','Volume']]
Y = df['CO2']


lr = linear_model.LinearRegression()

lr.fit(X, Y)

predictedCO2=lr.predict([[2300,1300]])
print(predictedCO2)